{{- if .Values.pipeline.enabled -}}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helloworld
spec:
  params:
  - name: appendix
    type: string
    default: {{ .Values.pipeline.helloWorld.appendix }}
    description: "this stores a name to the httpd webserver app"
  tasks:
    - name: write-name
      taskRef:
        name: write-name
      params:
      - name: appendix
        value: $(params.appendix)
  tasks:
    - name: recreate-homepage
      taskRef:
        name: create-configmap
      params:
      - name: appendix
        value: $(params.appendix)
{{- end }}