{{- if .Values.route.enabled -}}
{{- $fullName := include "tekton-test.fullname" . -}}
{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "tekton-test.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "tekton-test.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{ if .Values.route.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
  wildcardPolicy: None
{{- end }}
{{- end }}